name: 'Fetch news'

on:
  schedule:
    - cron: "0 6,18 * * *"

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        run: git@github.com:responsible-ai-collaborative/nlp-monitoring.git

